### PR TITLE
Rename virtual modules to use a colon : as a separator

### PR DESCRIPTION
**Pull request by altsalt**
Goal is to resolve https://github.com/astrolicious/astro-theme-provider/issues/80 which allows for `export` statements in `package.json`.

### CODE REVIEW

**Comment by altsalt** [comment]
Tests are currently not working, so I probably missed something, or it wasn't as simple as initially indicated.

```
      ✖ should resolve virtual modules (8.89868ms)
        AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
        + actual - expected
        
        + undefined
        - '\x00theme-mock/config'
            at TestContext.<anonymous> (file:///home/salt/Projects/astro-theme-provider/package/tests/theme.test.js:197:13)
            at Test.runInAsyncScope (node:async_hooks:206:9)
            at Test.run (node:internal/test_runner/test:631:25)
            at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
            at Test.postRun (node:internal/test_runner/test:715:19)
            at Test.run (node:internal/test_runner/test:673:12)
            at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7) {
          generatedMessage: true,
          code: 'ERR_ASSERTION',
          actual: undefined,
          expected: '\x00theme-mock/config',
          operator: 'strictEqual'
        }

      ✖ should generate virtual modules (11.186552ms)
        AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
        
        false !== true
        
            at TestContext.<anonymous> (file:///home/salt/Projects/astro-theme-provider/package/tests/theme.test.js:216:14)
            at Test.runInAsyncScope (node:async_hooks:206:9)
            at Test.run (node:internal/test_runner/test:631:25)
            at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
            at Test.postRun (node:internal/test_runner/test:715:19)
            at Test.run (node:internal/test_runner/test:673:12)
            at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7) {
          generatedMessage: true,
          code: 'ERR_ASSERTION',
          actual: false,
          expected: true,
          operator: 'strictEqual'
        }

      ✖ should override virtual modules (8.353386ms)
        TypeError [Error]: overrides[key] is not iterable
            at TestContext.<anonymous> (file:///home/salt/Projects/astro-theme-provider/package/tests/theme.test.js:241:34)
            at Test.runInAsyncScope (node:async_hooks:206:9)
            at Test.run (node:internal/test_runner/test:631:25)
            at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
            at Test.postRun (node:internal/test_runner/test:715:19)
            at Test.run (node:internal/test_runner/test:673:12)
            at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7)
```

**Comment by altsalt** [comment]
Found the ones I was missing. Tests are now completing.

**Comment by altsalt** [comment]
Hmm, when I attempt to test this locally via a linked package, it throws a `Cannot find module 'my-theme:styles' imported from...` error. Unsure if the problem is in my template modifications or here.

**Review by BryceRussell — APPROVED** [review]
LGTM 🚀 I fixed a few modules that got missed in the theme playground. Thanks for tackling this issue!

**Pull request merged**
